### ISSUE TITLE
[Feature Request] Adding some more Fleet options

### ISSUE THREAD

**Issue by PervyJoker** [ppfeufer/aa-fleetpings#132]
i have had a few corp mates annoying me with this and they want to add a feature where they can select "Mining Fleet" As an option for the Fleet Type selection. is it possible you can add this simple humble request for me so i can shut up my corp mates ? :) i told them to just edit the text themselfs before they paste it but nopp, too hard for them to do -.-

**Comment by ppfeufer** [comment]
Check the app setting in your Django Admin Backend, you can add fleet types there.
