### ISSUE TITLE
[Feature Request] Relative time for Discord pings

### ISSUE THREAD

**Issue by ehawman** [ppfeufer/aa-fleetpings#178]
### Context

In which context would you expect your suggested feature to be useful?

Seeing the relative time is quite nice, esp when you expect a fleet later this afternoon but you've missed that the date is for tomorrow (based on real events).

### Describe the feature you have in mind

When generating the ping text, just append the relative time to the end of the local time string.

`**Formup (Local Time):** <t:1710532800:F> <t:1710532800:R>`

### Additional context

Add any other context or screenshots/mockups about the feature request here.

![image](https://github.com/ppfeufer/aa-fleetpings/assets/52979227/c4fdb39f-cfb2-498c-a77a-6731bc0cedd0)

1st has a space between, 2nd doesn't.

**Comment by ppfeufer** [comment]
Nice idea!

**Comment by ppfeufer** [comment]
![image](https://github.com/ppfeufer/aa-fleetpings/assets/2989985/dc60adb1-b451-4e9b-9d48-7e760ab33449)

**Comment by ehawman** [comment]
Sweet! Thank you!
