### ISSUE TITLE
Weird encoding when typing > in Doctrine field (and others)

### ISSUE THREAD

**Issue by ehawman** [ppfeufer/aa-fleetpings#185]
### Bug Description

When trying to use < or > in the Fleet comms, Doctrine, or Formup Location fields (tested FC name, Fleet name, and Additional information fields and they don't exhibit this behavior), it toggles into a weird encoding loop.
`Test text&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;gt; dje`

### Steps to Reproduce

1. Click into one of the affected fields.
2. Press `Shift+.` to insert a `>`
3. Watch as each key press (including releasing `.` and `Shift` are converted into `&amp;amp;gt;`)

### Expected behavior

`>`

### Please complete the following information:

- App Version:  (will get from site host)
- Alliance Auth Version: (will get from site host)
- Browser and Version: Chrome 123.0.6312.58

### Additional context

Oh whoa it does it for `'` as well. 

The only way to escape this mode is to triple-click left-mouse until you've highlighted all text, then backspace to delete.

**Comment by ppfeufer** [comment]
Interesting.

From what I could find, this is related to a bug in a JS library I'm using for this » https://github.com/sergiodlopes/jquery-flexdatalist/issues/230

I give it a couple of weeks to see if the dev of that lib is going to implement the promised patch or not and be looking for alternatives …

**Comment by ehawman** [comment]
Thank you!
