### ISSUE TITLE
[Feature Request] Add fittings module link to embed

### ISSUE THREAD

**Issue by swashman** [ppfeufer/aa-fleetpings#222]
### Context

Make use of the doctrines and fittings model beyond the form. Resulting embed doesn't include a link.

### Describe the feature you have in mind

Embed or generated ping should have fitting module link as opposed to just the name of the doctrine/fitting

**Comment by ppfeufer** [comment]
I'm pretty sure the link is there already.

![image](https://github.com/user-attachments/assets/6f633fd7-8fa8-41ff-b78e-bf6a7666d9ca)

![image](https://github.com/user-attachments/assets/24185517-8dbe-44ec-9bad-5264a8afd31b)

**Comment by swashman** [comment]
Oh! Checked through the code and didn't see it there either, but I guess I missed something.
My apologies, will go through my setup. Something must be outdated or wrong somewhere that I didn't notice.
