### ISSUE TITLE
[Feature Request] have the system tell you about the eve time selection

### ISSUE THREAD

**Issue by Silly-123123** [ppfeufer/aa-fleetpings#237]
hey there, 

me specificly, but also some members of the alliance keep making the mistake on the fleet pings. due to time. 

can we have a sentence under the Formup Time that states its EVE time your selecting, in stead of local time?

greetings 

Phantom
![image](https://github.com/user-attachments/assets/c0f626ff-d0fd-412f-9678-a61fb7a681ee)

**Comment by ppfeufer** [comment]
Hope that's sufficient enough …
![image](https://github.com/user-attachments/assets/334a7312-9e9c-4215-a175-a92fe4c3cf1b)
