### ISSUE TITLE
Enchantment: No ping target and default selections

### ISSUE THREAD

**Issue by paulipa** [ppfeufer/aa-fleetpings#31]
We are trying to keep the amount of pings to minimum on our discord and would prefer to have a no ping target option as well on the default options. This would allow us to send pre pings without pings :) 

Also the ability to select the default option for ping target and ping channel would be awesome or ability to disable format ping for me option as we have no use for this

Edit: And yes for anyone who wants to do this until and if this is implemented you can always do these changes locally on the template files until that

**Comment by ppfeufer** [comment]
> We are trying to keep the amount of pings to minimum on our discord and would prefer to have a no ping target option as well on the default options. This would allow us to send pre pings without pings :)

I can add that one



> Also the ability to select the default option for ping target and ping channel would be awesome or ability to disable format ping for me option as we have no use for this

No. Ping targets (other than the ones defined by default) and ping channels can be restricted to different groups. This makes it pretty much impossible to assign defaults.
