### ISSUE TITLE
Sanitize inputs

### ISSUE THREAD

**Issue by paulipa** [ppfeufer/aa-fleetpings#38]
Double quotes in fields cause pings not no pass to discord. Should sanitize all fields and remove weird and possible harmful characters.

Noticed when tried to add ingame channel name in additional details in double quotes.

**Comment by ppfeufer** [comment]
Couldn't reproduce he behavior you are describing

![591421e7e1e7](https://user-images.githubusercontent.com/2989985/99259446-54afcc00-281a-11eb-9b49-1a716b82b0c3.jpg)

But I found that doctrines that have a " somewhere in their name will break it.

**Comment by ppfeufer** [comment]
![17486c3fe8f5](https://user-images.githubusercontent.com/2989985/99263663-cb9b9380-281f-11eb-9ab2-d45b06411379.jpg)

**Comment by paulipa** [comment]
yeah issue seemed to be focused on the doctrine field. Our guys used `see channel "my fits" for fits`

**Comment by ppfeufer** [comment]
Get a fitting page :-P

https://gitlab.com/colcrunch/fittings and let the fleetpings app link to the doctrine directly :-)
