### ISSUE TITLE
Fleet types are not showing up in the Admin panel

### ISSUE THREAD

**Issue by Jasonvdoorn** [ppfeufer/aa-fleetpings#42]
Hi,

I have setup a few fleet types for our fleet ping but it seems that they are now gone in the Admin panel.
Any idea on how we could fix this?

<img width="517" alt="Adminpanel" src="https://user-images.githubusercontent.com/14273560/104124608-0a4a5780-5352-11eb-9b0d-da86bd9baac9.PNG">
<img width="793" alt="Fleettypeping" src="https://user-images.githubusercontent.com/14273560/104124609-0ae2ee00-5352-11eb-895e-667a0615392a.PNG">

**Comment by ppfeufer** [comment]
That's an odd one. Thanks for letting me know, I'll have a look at it ...

**Comment by ppfeufer** [comment]
Dang wait ... for a moment you bamboozled me there ...

These are the default fleet types that are always there.  You can't change those.

**Comment by Jasonvdoorn** [comment]
Oww my bad!
I thought I created these myself and some update screw it..

Alright thanks!
