### ISSUE TITLE
Pre ping title includes indication that the fleet is already up

### ISSUE THREAD

**Issue by paulipa** [ppfeufer/aa-fleetpings#61]
When creating pre pings with the pre ping option selected the title of the ping is misleading indicating also that the flee is already up. Reformatting this phrase or removing it will reduce confusions between pre pings and actual fleet pings
![image](https://user-images.githubusercontent.com/8478738/147137048-8f51cf77-5d14-4498-8c23-ab874f542f68.png)

**Comment by ppfeufer** [comment]
I don't see how this is confusing, it clearly says `### PRE PING ###` in big letters right there ...

**Comment by paulipa** [comment]
The part that is confusing is that it says its under the fc which indicates its up already. At least as a non native speaker that is what it sound to me. If it would say something like is hosted by or will be under by it would sound like that it is not yet up.

**Comment by ppfeufer** [comment]
Then keep the FC field empty ...

**Comment by paulipa** [comment]
We prefer to keep it up there so that people can contact the FC if they have any questions about the upcoming fleets. But i guess this is just a personal matter on how we tend to interpret the phrase so ill just leave this in here in case more people feels like that as well. If not can simply close :)
