### ISSUE TITLE
[Feature Request] Discord timestamp conversion support.

### ISSUE THREAD

**Issue by MorphedAU** [ppfeufer/aa-fleetpings#70]
Rather then having a link to the timezone conversion page (or just dealing with EVE time conversions which some people seem to have trouble with) using the Discord timestamp conversion would show the time in the viewers current timezone.

Not sure if it can be used in embeds. But entering <t:1649212436:F> in Discord for myself returns "Wednesday, 6 April 2022 10:33"
The relative flag can also be used to return "in 32 minutes" <t:1649215376:R> and updates as time goes on (See https://hammertime.djdavid98.art/ for available formats).

I'm envisioning the pings to be updated to show:

Formup EVE Time: 2022-04-12 10:00 ( <t:1649757600:R> ) - relative timestamp (in 6 days)
Formup Local Time: <t:1649757600:F> - Full timestamp of Tuesday, 12 April 2022 18:00 )

**Comment by ppfeufer** [comment]
Unfortunately, this is not reliable, since it uses the system's timezone configuration, which can differ from the actual timezone the user is in.

**Comment by MorphedAU** [comment]
uses the system's timezone configuration, which can differ from the actual timezone the user is in.
- so does the Timezone Conversion page that gets linked when installed. Also I'd like to think if someones system is running in a different timezone, the user would be aware of that.

Doesn't work for systems with multiple configured timezones
- fair, i've never encountered systems with multiple configured timezones and don't know how discord handles that.

doesn't work in the copy/paste text
- playing around with this in the additional text area, as long as its entered as HTML encoded it works for copy and paste (but obviously not the webhook ping). It should be possible to get it to work for both.
`Test &lt;t:1659209080:F&gt;`

I'd be happy to try and add this in myself in a couple of weeks once I'm done moving house, making it a checkbox so that it can be chosen when making the ping.

**Comment by ppfeufer** [comment]
I'm currently fiddling around with it, I had this on my list for quite some time but ran into a couple of roadblocks.

The TZ conversion page handles differently configured timezones much better than Discord does. Discord relies solely on the `<t>` tag, which the page doesn't.

**Comment by ppfeufer** [comment]
Ok, let's ignore systems with multiple timezones for now. Not sure how Windows handles this, but on Linux, there is a primary timezone that is taken into account here and works quite well ...

**Comment by ppfeufer** [comment]
If you like, you can test already. Let me know if it is what you had in mind

https://pypi.org/project/aa-fleetpings/2.13.0b1/
