### ISSUE TITLE
Custom ping targets not auto-linking in Discord properly.

### ISSUE THREAD

**Issue by tonytonyistony** [ppfeufer/aa-fleetpings#74]
### Bug Description

When using a custom ping target, the @group doesn't actually get auto linked to create the ping.

### Steps to Reproduce

1. Create custom ping target
2. Go to Fleet pings app
3. Design a fleet ping and add your custom ping group to the fleet notification
4. Ping goes out normally except the @ target isn't auto linked.
Our last known good fleet ping was on the 18th.

### Expected behavior

When a ping goes out using the ping group, it auto links the group properly.

### Screenshots

![image](https://user-images.githubusercontent.com/53504611/164363601-a35fb7ea-36a1-45b7-ac58-4ddd2e6375f9.png)

### Please complete the following information:

- App Version: 2.13.1
- Alliance Auth Version: 2.11.2
- Browser and Version: Brave V1.37.116

### Additional context

If I copy and paste from the "Formatted Ping Text" into the channel it works properly.

**Comment by ppfeufer** [comment]
Hey there,

Thanks for reporting this. It seems to be an issue with spaces in the name. I'll have a look at it ...

**Comment by ppfeufer** [comment]
That should do the trick now

![image](https://user-images.githubusercontent.com/2989985/164457018-16e28c6e-e51f-458c-93f7-2e22e707aa0a.png)

Release coming soon
